[package]
name = "day14"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2016-14"

[[bin]]
name = "aoc-2016-14"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.10.0"
md5 = "0.7.0"
