[package]
name = "day18"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2019-18"

[[bin]]
name = "aoc-2019-18"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.8.1"
