[package]
name = "day06"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2021-6"

[[bin]]
name = "aoc-2021-6"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.9.1"
lazy_static = "1.4.0"
