[package]
name = "day15"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2021-15"

[[bin]]
name = "aoc-2021-15"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.9.1"
grid = "0.6.0"
shared = { path = "../shared" }
