[package]
name = "day17"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2016-17"

[[bin]]
name = "aoc-2016-17"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.8.1"
md5 = "0.7.0"
