[package]
name = "day05"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2015-5"

[[bin]]
name = "aoc-2015-5"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.8.1"
fancy-regex = "0.4.1"
lazy_static = "1.4.0"
