[package]
name = "day23"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2015-23"

[[bin]]
name = "aoc-2015-23"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.9.1"
