[package]
name = "day19"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2018-19"

[[bin]]
name = "aoc-2018-19"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.10.0"
shared = { path = "../shared" }
