#!/usr/bin/env bash

set -e

pushd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )"

if [ "$#" -eq 2 ]; then
  year=$1
  day=$( printf %02d $2 )
elif [ "$#" -eq 1 ]; then
  year=$( date +%Y )
  day=$( printf %02d $1 )
else
  echo "Usage: $0 <year> <day>"
  exit 1
fi

if [ ! -f "AoC$year/AoC$year.sln" ]; then
  echo "Creating solution AoC$year"
  mkdir -p AoC$year
  pushd AoC$year
  dotnet new sln
else
  pushd AoC$year
fi


echo "Creating project Day$day in solution AoC$year"

set -x

dotnet new aocsolution --language 'F#' --output Day$day
dotnet sln add Day$day

popd
