[package]
name = "day21"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2017-21"

[[bin]]
name = "aoc-2017-21"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.9.0"
grid = "0.6.0"
bytecount = "0.6.2"
