[package]
name = "day16"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2020-16"

[[bin]]
name = "aoc-2020-16"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.10.0"
