#!/usr/bin/env bash

set -e

pushd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )"

if [ "$#" -eq 2 ]; then
  year=$1
  day=$( printf %02d $2 )
elif [ "$#" -eq 1 ]; then
  year=$( date +%Y )
  day=$( printf %02d $1 )
else
  echo "Usage: $0 <year> <day>"
  exit 1
fi

if [ ! -f "AoC$year/AoC$year.sln" ]; then
  echo "Solution AoC$year does not exist"
  exit 1
else
  pushd AoC$year
fi

echo "Removing project Day$day from solution AoC$year"

set -x

dotnet sln remove Day$day
rm -r Day$day
