#!/usr/bin/env bash

set -e

if [ "$#" -eq 2 ]; then
  year=$1
  day=$( printf %02d $2 )
elif [ "$#" -eq 1 ]; then
  year=$( date +%Y )
  day=$( printf %02d $1 )
else
  echo "Usage: $0 <year> <day>"
  exit 1
fi

echo "Removing project Day$day from solution AoC$year"

set -x

dotnet sln remove Day$day
dotnet sln remove Day$day.Test
rm -r Day$day Day$day.Test
