[package]
name = "day18"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2018"
default-run = "aoc-2018-18"

[lib]
name = "forest"
path = "src/forest/lib.rs"

[[bin]]
name = "aoc-2018-18"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.5.0"
