[package]
name = "day20"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2018"
default-run = "aoc-2017-20"

[[bin]]
name = "aoc-2017-20"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.6.4"
