[package]
name = "day20"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2019-20"

[lib]
name = "maze"
path = "src/maze/lib.rs"

[[bin]]
name = "aoc-2019-20"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.10.0"
grid = "0.9.0"
