[package]
name = "day05"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2018"
default-run = "aoc-2016-5"

[[bin]]
name = "aoc-2016-5"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.5.0"
rust-crypto = "0.2.36"
