[package]
name = "day25"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2018"
default-run = "aoc-2017-25"

[lib]
name = "turing_machine"
path = "src/lib/mod.rs"

[[bin]]
name = "aoc-2017-25"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.6.5"
