[package]
name = "day04"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2020-4"

[[bin]]
name = "aoc-2020-4"
path = "src/main.rs"

[dependencies]
regex = "1"
rdcl_aoc_helpers = "0.8.1"
