[package]
name = "day08"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2019-8"

[[bin]]
name = "aoc-2019-8"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.8.1"
grid = "0.6.0"
