[package]
name = "day09"
version = "0.1.0"
authors = ["Ruud van der Weide <rj@rdcl.dev>"]
edition = "2021"
default-run = "aoc-2015-9"

[[bin]]
name = "aoc-2015-9"
path = "src/main.rs"

[dependencies]
rdcl_aoc_helpers = "0.8.1"
shared = { path = "../shared" }
