name: "CI 2016"

on:
  push:
    branches:
      - '**'
    paths:
      - '2016/**'

defaults:
  run:
    working-directory: 2016

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
