name: "F# 2021"

on:
  push:
    branches:
      - '**'
    paths:
      - 'fsharp/AoC2021/**'
      - '.github/workflows/ci-fsharp-2021.yml'

defaults:
  run:
    working-directory: fsharp/AoC2021

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - uses: actions/checkout@v2
      - name: build
        run: dotnet build
      - name: test
        run: dotnet test
