name: "python 2021"

on:
  push:
    branches:
      - '**'
    paths:
      - 'python/2021/**'
      - '.github/workflows/ci-python-2021.yml'

defaults:
  run:
    working-directory: python/2021

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --statistics
      - name: Test with pytest
        run: pytest
